### ISSUE TITLE
这个 fork 版本的目标是什么

### ISSUE THREAD

**Issue by yinjimmy** [CaptainCN/quick-x#1]

**Comment by CaptainCN** [comment]
保持之前quick拥有功能的前提下，使他更好用。当然那些重复的功能，会被删掉。比如什么menu，controlbutton，studio UI，全部统一用studio这个ui

**Comment by CaptainCN** [comment]
有兴趣，可以一起

**Comment by yinjimmy** [comment]
计划改进的功能有哪些呢？

**Comment by CaptainCN** [comment]
目前先整理目录结构吧。主要要重新做事件系统，废弃之前xxx_selector 这种。
我的QQ在我的另外一个[项目](https://github.com/CaptainCN/QCEditor)里面有。可以加我聊
